dataset:
  train_num: 10000
  lf0_low: 5.7
  lf0_high: 6.7
  sampling_rate: 24000
  min_sampling_length: 100
  max_sampling_length: 100
  test_num: 100
  seed: 0

network:
  hidden_size: 32
  block_num: 8
  post_layer_num: 0

model: {}

train:
  diffusion_step_num: 10
  batch_size: 64
  eval_batch_size: 16
  log_epoch: 1
  eval_epoch: 5
  snapshot_epoch: 5
  stop_epoch: 300
  model_save_num: 10
  optimizer:
    name: "adam"
    lr: 0.0051
    weight_decay: 0.0001
  scheduler:
    name: warmup
    warmup_steps: 2000
  weight_initializer: xavier_uniform
  use_gpu: true
  use_amp: true

project:
  name: null
  tags:
    task_name: null
  category: check_diffusion_sine
